version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
    container_name: jenkins
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

networks:
  jenkins:
    driver: bridge
